# Generated by Django 4.2.6 on 2023-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='character',
            name='anime_debut',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='title',
        ),
        migrations.AddField(
            model_name='arc',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
