# Generated by Django 4.2.6 on 2023-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_character_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saga',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
